package com.zcb.minimalldb.dao;

import com.zcb.minimalldb.domain.GoodsSpecification;
import com.zcb.minimalldb.domain.GoodsSpecificationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    long countByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int insert(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsSpecification selectOneByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsSpecification selectOneByExampleSelective(@Param("example") GoodsSpecificationExample example, @Param("selective") GoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GoodsSpecification> selectByExampleSelective(@Param("example") GoodsSpecificationExample example, @Param("selective") GoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    List<GoodsSpecification> selectByExample(GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    GoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsSpecification record, @Param("example") GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsSpecification record, @Param("example") GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") GoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}