package com.zcb.minimalldb.dao;

import com.zcb.minimalldb.domain.Keyword;
import com.zcb.minimalldb.domain.KeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    long countByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int deleteByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int insertSelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Keyword selectOneByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Keyword selectOneByExampleSelective(@Param("example") KeywordExample example, @Param("selective") Keyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Keyword> selectByExampleSelective(@Param("example") KeywordExample example, @Param("selective") Keyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    List<Keyword> selectByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Keyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Keyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    Keyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Keyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}