package com.zcb.minimalldb.dao;

import com.zcb.minimalldb.domain.SearchHistory;
import com.zcb.minimalldb.domain.SearchHistoryExample;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    long countByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int deleteByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int insert(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int insertSelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SearchHistory selectOneByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SearchHistory selectOneByExampleSelective(@Param("example") SearchHistoryExample example, @Param("selective") SearchHistory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SearchHistory> selectByExampleSelective(@Param("example") SearchHistoryExample example, @Param("selective") SearchHistory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    List<SearchHistory> selectByExample(SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SearchHistory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    SearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SearchHistory record, @Param("example") SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SearchHistory record, @Param("example") SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);

    /**
     * @param keyword
     * @param beginTime
     * @param endTime
     * @param limit
     * @return
     */
    List<String> queryHotSearch(String keyword, Boolean deleted, LocalDateTime beginTime, LocalDateTime endTime, int limit);
}