pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql


# 数据库配置
# Minimall.123
# privateKey:MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAoXJmG5K4jkRo6604TpSlOqkN2UIqchMPIDLYp5PlPKHiYNZk7i1ap7ALt8O+tf+KFi5bEyUx8Ov96a483tfowQIDAQABAkAhOXi37e7bIErzTVeMHF0QgF/gORShGzj+qFgbzHzdiCK8rj11riKDNaUdZOeQGpBohQ66g8Mot6GeVrEtTY79AiEA52IDSW6MAJjrZffyZZu9SQjRgFXLMXE3emEVJlSsSKcCIQCyn5ifoOSi+iHvIUk8ARF7SPlUwlpx2IDcBlLnlIoIVwIgdPJQ/vhkwpiHwc4EMd75WMSgPuEeBitXAv+2lN0PBtkCIHCyuzPz6m1dje13PeKK9gGn8A/nM/NiWyL3JnWQRWqvAiEAq0vK8RrVYUtp+yOY94N1GrTGnZLwN7DqsQbc2LOAoMU=
# publicKey:MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFyZhuSuI5EaOutOE6UpTqpDdlCKnITDyAy2KeT5Tyh4mDWZO4tWqewC7fDvrX/ihYuWxMlMfDr/emuPN7X6MECAwEAAQ==
# password:VpMe8FclztkdP1xdJ/Mh8EX47kkSCrqN8wZ4LSoDArJZXcPRhvFy6KeK2RRhsl2qW3BX2yR6nXB7k2VFm72V5w==
# https://github.com/alibaba/druid
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/minimall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: VpMe8FclztkdP1xdJ/Mh8EX47kkSCrqN8wZ4LSoDArJZXcPRhvFy6KeK2RRhsl2qW3BX2yR6nXB7k2VFm72V5w==
      driver-class-name: com.mysql.jdbc.Driver
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,config,wall
      useGlobalDataSourceStat: true
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFyZhuSuI5EaOutOE6UpTqpDdlCKnITDyAy2KeT5Tyh4mDWZO4tWqewC7fDvrX/ihYuWxMlMfDr/emuPN7X6MECAwEAAQ==

# mybatis配置
mybatis:
  # mapper-locations: classpath*:mapper/*.xml #指定映射的文件，默认加载的是同一包下的同名.xml文件
  config-location: classpath:config/mybatis-config.xml

# 打印sql语句
logging:
  level:
     com.zcb.minimalldb.dao: debug


